### ISSUE TITLE
media query stuff on mobile and small screen

### ISSUE THREAD

**Issue by edifyedu** [edifyedudesign/edifyedudesign.github.io#32]
@elauervose can you take a look at this?

make id tags land in the right place

**Comment by elauervose** [comment]
### Apple Products Issues

| Issue | iPhone 4 | iPhone 5 | iPhone 6 & 6+ | iPad 7 iPad mini |
| --- | :-: | --: | --: | --: |
| footer width too small | X | X |  |  |
| About section ID too low | X | X | X |  |
| Services section ID too low |  | X |  |  |
| Blog - broken | X | X | X |  |
| Contact section ID too low | X | X | X |  |
| Mail Chimp form too wide | X | X | X |  |

**Comment by elauervose** [comment]
## Mobile Devices Reviewed

![screen shot 2015-06-10 at 3 21 13 pm](https://cloud.githubusercontent.com/assets/4341415/8095593/62033824-0f84-11e5-808f-fae741cd6548.png)

**Comment by elauervose** [comment]
Am working on fixing blog responsiveness - made a mess and need to get help from CHuck to revert to the last commit that was good (they are in the pull request I made).

In the meantime, I want to document an other easy fix ( you can do this if you want to) 

### This fixes the collapsed nav bar in the blog

_It's currently turning blue_

First, delete the class "colorskin-1" from the default-blog layout
![screen shot 2015-06-11 at 12 14 16 pm](https://cloud.githubusercontent.com/assets/4341415/8115944/ced71646-1033-11e5-9dc2-57fcab248534.png)

then, delete or comment out the color-skins.css file in the "head" file. 
![screen shot 2015-06-11 at 12 13 54 pm](https://cloud.githubusercontent.com/assets/4341415/8115965/f23a3bb8-1033-11e5-9cef-25fc6685b9db.png)

**Comment by elauervose** [comment]
Finally got it!! There is a little tidying up that I want to do so it's clear which stylesheets belong to which themes, but this is good enough to tweet about!! :) Yeay!!
