### ISSUE TITLE
Add About Header to About Section

### ISSUE THREAD

**Issue by elauervose** [edifyedudesign/edifyedudesign.github.io#37]
Do you want this? 
*I think it's Important for SEO as well as consistency

**Comment by edifyedu** [comment]
hmm... i think adding a header here will disrupt the flow, but I can look again and try.

**Comment by elauervose** [comment]
I added the header back in in an attempt to fix some mobile issues - didn't quite work (yet) so I can delete the header again if you want ...

![screen shot 2015-06-10 at 4 50 44 pm](https://cloud.githubusercontent.com/assets/4341415/8096884/e495974e-0f90-11e5-8fd5-1dc7e4b5471d.png)
