### ISSUE TITLE
Contact Form: does this go anywhere? 

### ISSUE THREAD

**Issue by elauervose** [edifyedudesign/edifyedudesign.github.io#45]
Make it go somewhere or delete
- if keeping, make border green & highlight to blue

![screen shot 2015-06-09 at 11 08 04 am](https://cloud.githubusercontent.com/assets/4341415/8065696/00d4663c-0e98-11e5-9eb7-0fd50287fc2d.png)

**Comment by edifyedu** [comment]
I'm not sure where this goes - how do we connect it to my email?

**Comment by elauervose** [comment]
I will talk to Chuck and see what's possible
