### ISSUE TITLE
On Large Monitor: Paralax image repeat is showing under the "about founder" section

### ISSUE THREAD

**Issue by elauervose** [edifyedudesign/edifyedudesign.github.io#49]
Not sure if you care about this - feel free to mark this "won't fix" since it's really pretty minor

**Comment by edifyedu** [comment]
this has been happening for a while - tried to fix it today and got almost there.

**Comment by elauervose** [comment]
I'll take a stab at it after the mobile stuff is fixed

**Comment by edifyedu** [comment]
Decided not to work on this.
