### ISSUE TITLE
Minor issue: punctuation at the end of some headers and not others

### ISSUE THREAD

**Issue by elauervose** [edifyedudesign/edifyedudesign.github.io#50]
Do you care one way or the other?

![screen shot 2015-06-09 at 11 16 46 am](https://cloud.githubusercontent.com/assets/4341415/8065874/280ee78a-0e99-11e5-96b1-e3e6d3469c7a.png)

![screen shot 2015-06-09 at 11 17 08 am](https://cloud.githubusercontent.com/assets/4341415/8065877/2c4a9470-0e99-11e5-99a3-a1667bbffe60.png)

**Comment by edifyedu** [comment]
will do - this will be my to-do.
