### ISSUE TITLE
Fix Favicon 

### ISSUE THREAD

**Issue by elauervose** [edifyedudesign/edifyedudesign.github.io#51]
Do you have a tiny icon you like?
Right now, it's just showing the last image local host used which is my blog icon - I have used just the first 1 or 2 letters of a title in the past - ie. you could have: 

![favicon1](https://cloud.githubusercontent.com/assets/4341415/8066075/7483dd40-0e9a-11e5-991f-a3412d7c1efd.png)

OR

![favicon2](https://cloud.githubusercontent.com/assets/4341415/8066081/7b9efd76-0e9a-11e5-9ab8-9017a5b09ac8.png)

**Comment by elauervose** [comment]
Just realized you have a favicon on your WP site ... do you have a jpg for it? 

![screen shot 2015-06-09 at 5 40 48 pm](https://cloud.githubusercontent.com/assets/4341415/8072710/bb1e09a4-0ece-11e5-95d4-7b2defe020b3.png)

**Comment by edifyedu** [comment]
can we do a really small version of edify? the one on the WP site is actually an old logo.

**Comment by elauervose** [comment]
I'll pit in "edify" and you can see what you think ... it may end up being too small but I'll let you decide :smile:

**Comment by edifyedu** [comment]
still not seeing the favicon show up :(

**Comment by edifyedu** [comment]
Deciding not to work on this.
