### ISSUE TITLE
LinkedIn link in footer points to Github instead

### ISSUE THREAD

**Issue by thorprichard** [edifyedudesign/edifyedudesign.github.io#61]
Minor, but probably good to fix at some point.  

PS:  Awesome that you're doing this on GitHub.  +1.

**Comment by edifyedu** [comment]
Agh thank you! Will fix today :)

On Tuesday, June 23, 2015, Thor Prichard notifications@github.com wrote:

> Minor, but probably good to fix at some point.
> 
> PS: Awesome that you're doing this on GitHub. +1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/edifyedudesign/edifyedudesign.github.io/issues/61.

## 

Cheers,

Kristen Gallagher
Founder, Edify Education Design
503 734 0839
www.edifyedu.com
@edifyedu

Grow your company with Edify's monthly letter - find it here!
http://eepurl.com/3sx29
